import type { Contributor, PullRequest, SubsystemId } from './types'

// Every person, review, and change below is independently authored fiction.
const record = (
  id: number,
  title: string,
  authorId: string,
  mergedAt: string,
  subsystemIds: SubsystemId[],
  summary: string,
  reviewerId: string,
  review: string,
  file: string,
  diff: string,
): PullRequest => ({
  id: `PR-${id}`,
  title,
  authorId,
  mergedAt,
  subsystemIds,
  summary,
  reviews: [{ contributorId: reviewerId, excerpt: review }],
  file,
  diff,
})

export const expandedContributors: Contributor[] = [
  {
    id: 'theo',
    name: 'Theo Marin',
    initials: 'TM',
    title: 'Identity engineer',
    color: 'blue',
    bio: 'Designs identity-provider boundaries and consent flows. His PRs show implementation and review of authentication interfaces, with one older migration record.',
  },
  {
    id: 'imani',
    name: 'Imani Reed',
    initials: 'IR',
    title: 'Security engineer',
    color: 'rose',
    bio: 'Works on account recovery safeguards and authentication auditability. Her contributions focus on abuse resistance rather than general incident recovery.',
  },
  {
    id: 'sofia',
    name: 'Sofia Petrov',
    initials: 'SP',
    title: 'Client platform engineer',
    color: 'purple',
    bio: 'Connects browser session behavior to server contracts. Her examples cover device sessions, reauthentication prompts, and client-safe error handling.',
  },
  {
    id: 'mateo',
    name: 'Mateo Ruiz',
    initials: 'MR',
    title: 'Ledger engineer',
    color: 'amber',
    bio: 'Builds invoice and ledger invariants. His records emphasize reconciliation and audit trails, with reviews that question ambiguous money state.',
  },
  {
    id: 'anika',
    name: 'Anika Rao',
    initials: 'AR',
    title: 'Subscriptions engineer',
    color: 'teal',
    bio: 'Works on subscription lifecycle and customer-visible billing history. Her PRs separate policy decisions from payment-provider mechanics.',
  },
  {
    id: 'owen',
    name: 'Owen Clarke',
    initials: 'OC',
    title: 'Payments integration engineer',
    color: 'olive',
    bio: 'Maintains provider integration edges such as webhook verification and retry-safe response mapping. The sample does not imply ownership of every billing service.',
  },
  {
    id: 'hana',
    name: 'Hana Kim',
    initials: 'HK',
    title: 'Queue engineer',
    color: 'teal',
    bio: 'Builds queue scheduling and worker coordination. Her changes show how leases, priorities, and shutdown handling affect delivery guarantees.',
  },
  {
    id: 'rafael',
    name: 'Rafael Costa',
    initials: 'RC',
    title: 'Workflow engineer',
    color: 'blue',
    bio: 'Works on long-running workflow state and retries. His reviewed PRs connect background jobs to billing without implying that he owns payments.',
  },
  {
    id: 'celine',
    name: 'Celine Dubois',
    initials: 'CD',
    title: 'Data operations engineer',
    color: 'rose',
    bio: 'Designs batch exports and job visibility for operators. Her sample changes cover checkpoints, cancellation, and failure explanations.',
  },
  {
    id: 'yusuf',
    name: 'Yusuf Haddad',
    initials: 'YH',
    title: 'Telemetry engineer',
    color: 'purple',
    bio: 'Shapes traces and metric dimensions for diagnosis. His records are about observing live systems, not documenting restore or recovery readiness.',
  },
  {
    id: 'grace',
    name: 'Grace Mensah',
    initials: 'GM',
    title: 'Reliability engineer',
    color: 'amber',
    bio: 'Improves alert quality and incident context. The available PRs show detection and triage signals, not tested disaster-recovery procedures.',
  },
  {
    id: 'quentin',
    name: 'Quentin Park',
    initials: 'QP',
    title: 'Developer experience engineer',
    color: 'olive',
    bio: 'Makes local debugging and trace inspection more useful. His contributions help explain system behavior while leaving production response ownership unproven.',
  },
]

export const expandedPullRequests: PullRequest[] = [
  record(
    125,
    'Bind SSO state to the initiating browser session',
    'theo',
    '2026-06-12',
    ['authentication'],
    'Associates the SSO state value with a short-lived browser session and rejects callbacks initiated elsewhere. The example covers a copied callback URL and a legitimate second tab.',
    'maya',
    'The state check belongs before account linking so a foreign tab cannot attach the response to the wrong session.',
    'auth/sso-state.ts',
    '+ if (callback.sessionId !== pending.sessionId) throw new InvalidSsoState()',
  ),
  record(
    126,
    'Explain identity-provider consent changes',
    'theo',
    '2026-04-20',
    ['authentication'],
    'Stores the requested and returned scopes separately so a sign-in can surface missing consent. This avoids silently treating a partial grant as a complete authorization.',
    'imani',
    'Please keep the raw provider token out of the diagnostic event; the scope names are enough to explain the mismatch.',
    'auth/consent.ts',
    '+ const missing = requestedScopes.filter(scope => !grantedScopes.has(scope))',
  ),
  record(
    127,
    'Reject duplicate external identity links',
    'theo',
    '2026-02-05',
    ['authentication'],
    'Adds a uniqueness boundary for external subject identifiers during account linking. A conflicting link returns an explicit error without changing either existing account.',
    'sofia',
    'The conflict response needs a stable client code but should not reveal which account already owns the external identity.',
    'auth/link.ts',
    '+ await identities.insertUnique({ provider, subject, accountId })',
  ),
  record(
    128,
    'Add the initial provider profile mapper',
    'theo',
    '2025-09-14',
    ['authentication'],
    'Introduces an early provider-profile mapper with a small set of normalized fields. Later account-linking checks should be read separately from this historical foundation.',
    'leah',
    'Keep optional provider fields optional in the normalized profile; a missing avatar must not block sign-in.',
    'auth/profile.ts',
    '+ return { subject: raw.sub, displayName: raw.name ?? null }',
  ),
  record(
    129,
    'Require a fresh factor for account recovery changes',
    'imani',
    '2026-06-03',
    ['authentication'],
    'Requires recent second-factor verification before changing recovery destinations. The flow expires the proof after one sensitive change and logs only safe metadata.',
    'maya',
    'The one-use proof closes the gap where a stale verification could authorize two destination changes.',
    'auth/recovery-factor.ts',
    '+ await factors.consumeRecentProof(accountId, proofId)',
  ),
  record(
    130,
    'Rate-limit repeated recovery code attempts',
    'imani',
    '2026-04-29',
    ['authentication'],
    'Tracks failed recovery-code attempts per account and challenge window. Lockout responses avoid confirming whether a guessed account or code exists.',
    'theo',
    'The window should reset after a successful challenge, while the audit event keeps the attempt count without the submitted code.',
    'auth/recovery-code.ts',
    '+ if (attempts.inWindow >= limit) return genericChallengeFailure()',
  ),
  record(
    131,
    'Record safe authentication decision reasons',
    'imani',
    '2026-01-23',
    ['authentication', 'observability'],
    'Adds coarse decision reasons for rejected sign-ins without emitting secrets or user-entered credentials. Operators can separate expired challenges from policy denials.',
    'nora',
    'Use an allow-list for reason labels so provider error text never becomes a metric dimension.',
    'auth/decision-event.ts',
    '+ emitAuthDecision({ reason: safeReason(error), accountRef })',
  ),
  record(
    132,
    'Document the original challenge threat cases',
    'imani',
    '2025-08-27',
    ['authentication'],
    'Adds historical examples for replayed challenges, clock skew, and abandoned sign-ins. These examples predate the newer one-use recovery proof.',
    'leah',
    'The examples make the intended boundary clear; note that they do not exercise provider outage behavior.',
    'auth/challenge-cases.md',
    '+ replayed challenge -> reject without account mutation',
  ),
  record(
    133,
    'Keep device sessions distinct in account settings',
    'sofia',
    '2026-06-17',
    ['authentication'],
    'Displays active device sessions using safe labels and last-seen dates. Revoking one device does not close the current session unless it is the selected target.',
    'eli',
    'The current-device marker needs to derive from the active session ID, not from matching a browser label.',
    'account/devices.vue',
    '+ const current = device.sessionId === activeSessionId',
  ),
  record(
    134,
    'Recover cleanly from expired reauthentication',
    'sofia',
    '2026-03-25',
    ['authentication'],
    'Preserves the intended account action while asking for a new authentication step. It drops the pending action if the account changes during the redirect.',
    'theo',
    'Clearing the action on account mismatch avoids replaying a sensitive change under another identity.',
    'account/reauth.ts',
    '+ if (returned.accountId !== pending.accountId) return discardAction()',
  ),
  record(
    135,
    'Distinguish revoked and expired sessions in UI copy',
    'sofia',
    '2026-02-19',
    ['authentication'],
    'Maps safe server session codes to distinct user-facing messages. The browser never tries to infer token contents or expose internal authentication details.',
    'maya',
    'The generic fallback is important when an unknown server code arrives from an older deployment.',
    'account/session-errors.ts',
    '+ return safeCopyByCode[error.code] ?? genericSignInCopy',
  ),
  record(
    136,
    'Introduce an early account session banner',
    'sofia',
    '2025-10-06',
    ['authentication'],
    'Adds a historical account banner for sign-in state and recent activity. Later device-level revocation behavior is not part of this early UI change.',
    'eli',
    'Use the server-provided last-seen date rather than relying on the browser clock for the displayed activity.',
    'account/session-banner.vue',
    '+ <AccountActivity :last-seen="session.lastSeenAt" />',
  ),
  record(
    137,
    'Balance ledger entries for invoice adjustments',
    'mateo',
    '2026-06-09',
    ['billing'],
    'Requires each invoice adjustment to produce equal debit and credit totals before posting. A failed balance check leaves the invoice and ledger unchanged.',
    'jonas',
    'The test should include a currency mismatch as well as an arithmetic imbalance; both must stop the post.',
    'billing/ledger-post.ts',
    '+ assertBalanced(entries)\n+ await ledger.postAtomically(entries)',
  ),
  record(
    138,
    'Trace credits to their originating invoice line',
    'mateo',
    '2026-04-14',
    ['billing'],
    'Stores a stable source line reference on credit entries. Reviewers can explain why a credit exists without guessing from the amount or creation time.',
    'anika',
    'Please keep the source reference even if the display label changes during a subscription migration.',
    'billing/credits.ts',
    '+ credit.sourceLineId = originalLine.id',
  ),
  record(
    139,
    'Reconcile settlement totals by currency',
    'mateo',
    '2026-01-30',
    ['billing'],
    'Compares provider settlements with posted ledger totals in separate currency buckets. Mismatches produce a reviewable report instead of a silent correction.',
    'owen',
    'A delayed provider event can be pending; label that case separately from a permanent amount mismatch.',
    'billing/reconcile.ts',
    '+ const difference = settledMinor - postedMinor',
  ),
  record(
    140,
    'Create the first immutable ledger entry shape',
    'mateo',
    '2025-08-18',
    ['billing'],
    'Introduces an early immutable ledger entry with amount, currency, and source reference. Later balancing rules are not implied by this historical type.',
    'leah',
    'Keeping the source reference required is useful even before the reconciliation job exists.',
    'billing/ledger-entry.ts',
    '+ type Entry = { amountMinor: bigint; currency: string; sourceId: string }',
  ),
  record(
    141,
    'Prorate upgrades against a locked period snapshot',
    'anika',
    '2026-06-14',
    ['billing'],
    'Calculates an upgrade against the saved subscription period rather than a mutable current plan. The resulting invoice line records the policy version used.',
    'mateo',
    'The policy version makes a future explanation possible when plan prices or proration rules change.',
    'billing/proration.ts',
    '+ return prorate(snapshot.period, snapshot.policyVersion, change)',
  ),
  record(
    142,
    'Show subscription transitions in billing history',
    'anika',
    '2026-04-07',
    ['billing'],
    'Adds a chronological record of trial, active, paused, and canceled transitions. The view separates an effective date from when the change was requested.',
    'eli',
    'A scheduled cancellation must read as future state; the current subscription remains active until its effective date.',
    'billing/history.ts',
    '+ history.push({ requestedAt, effectiveAt, from, to })',
  ),
  record(
    143,
    'Reject overlapping plan change requests',
    'anika',
    '2026-02-27',
    ['billing'],
    'Prevents two pending plan changes from assigning different future states to the same subscription period. The client receives a conflict it can resolve.',
    'jonas',
    'The comparison needs the period identifier, not just the subscription ID, because later periods are independent.',
    'billing/plan-change.ts',
    '+ assertNoPendingChange(subscriptionId, periodId)',
  ),
  record(
    144,
    'Seed early subscription lifecycle examples',
    'anika',
    '2025-11-10',
    ['billing'],
    'Adds historical examples for trial expiration and cancellation at period end. Those examples do not cover the later conflict and policy-version rules.',
    'leah',
    'The examples should retain the requested and effective dates so readers can tell them apart.',
    'billing/lifecycle-fixtures.ts',
    '+ { from: "trial", to: "active", effectiveAt: startAt }',
  ),
  record(
    145,
    'Verify payment webhook signature before parsing',
    'owen',
    '2026-06-25',
    ['billing'],
    'Checks the provider signature against raw request bytes before interpreting any event fields. Failed verification returns a generic rejection and schedules no work.',
    'imani',
    'Preserving raw bytes is necessary here; a JSON re-serialization can change the signed payload.',
    'billing/provider-webhook.ts',
    '+ const event = verifySignedPayload(rawBody, signature)',
  ),
  record(
    146,
    'Map provider declines to stable billing reasons',
    'owen',
    '2026-05-05',
    ['billing'],
    'Converts provider-specific decline codes into a small stable set of billing reasons. It retains the original code in restricted diagnostics only.',
    'jonas',
    'Unknown provider codes need a safe generic reason so UI behavior does not depend on an unmapped string.',
    'billing/declines.ts',
    '+ return knownDecline[providerCode] ?? "payment_unavailable"',
  ),
  record(
    147,
    'Separate webhook receipt from settlement work',
    'owen',
    '2026-03-02',
    ['billing', 'background-jobs'],
    'Acknowledges verified event receipt after a durable outbox write, while settlement occurs in a worker. Duplicate provider delivery retains the same event identity.',
    'priya',
    'The provider acknowledgement should follow the commit, and the consumer still needs its own idempotency check.',
    'billing/receipt.ts',
    '+ await outbox.commit(event)\n+ return acceptedReceipt(event.id)',
  ),
  record(
    148,
    'Add the original provider error translation',
    'owen',
    '2025-09-30',
    ['billing'],
    'Introduces a historical mapping of provider transport errors to billing service errors. It predates the newer stable decline taxonomy.',
    'leah',
    'The transport timeout must stay distinct from a card decline because a retry can be appropriate for only one of them.',
    'billing/provider-errors.ts',
    '+ if (error.kind === "timeout") return new RetryableProviderError()',
  ),
  record(
    149,
    'Schedule delayed jobs without polling every queue',
    'hana',
    '2026-06-22',
    ['background-jobs'],
    'Indexes the next eligible execution time so workers can sleep until useful work exists. A wake-up race rechecks the queue before idling.',
    'priya',
    'Please test an earlier job arriving while a worker waits; the notification must shorten the sleep.',
    'jobs/scheduler.ts',
    '+ await wakeAt(Math.min(nextEligibleAt, notificationAt))',
  ),
  record(
    150,
    'Drain leased work during planned shutdown',
    'hana',
    '2026-04-16',
    ['background-jobs'],
    'Stops claiming new jobs before shutdown while allowing bounded time for in-flight leases. Unfinished work becomes claimable after lease expiry.',
    'nora',
    'The deadline should be visible in diagnostics so an operator can tell a clean drain from a forced exit.',
    'jobs/shutdown.ts',
    '+ queue.stopClaims()\n+ await waitForInFlight({ deadlineMs })',
  ),
  record(
    151,
    'Keep priority lanes from starving routine jobs',
    'hana',
    '2026-02-11',
    ['background-jobs'],
    'Uses a weighted selection rule across urgent and routine job lanes. Tests show routine work still advances under a sustained urgent load.',
    'rafael',
    'The weights should be configuration with a bounded range, not a per-job override submitted by callers.',
    'jobs/priority.ts',
    '+ return lanes.pickWeighted({ urgent: 3, routine: 1 })',
  ),
  record(
    152,
    'Define the early job reservation record',
    'hana',
    '2025-08-04',
    ['background-jobs'],
    'Adds a historical reservation shape with worker and expiry fields. This first version does not implement later drain or fairness behavior.',
    'leah',
    'A reservation ID lets diagnostics distinguish a renewed lease from a new claim for the same job.',
    'jobs/reservation.ts',
    '+ type Reservation = { id: string; workerId: string; expiresAt: Date }',
  ),
  record(
    153,
    'Checkpoint multi-step export workflows',
    'rafael',
    '2026-06-11',
    ['background-jobs'],
    'Saves completed export steps so a retry resumes without repeating delivered pages. The checkpoint records a source cursor and an output version.',
    'celine',
    'Make the output version explicit; a new serializer should not reuse an old checkpoint without review.',
    'jobs/export-workflow.ts',
    '+ await checkpoint.save({ cursor, outputVersion })',
  ),
  record(
    154,
    'Expire waiting workflows with clear reasons',
    'rafael',
    '2026-04-03',
    ['background-jobs'],
    'Marks workflows that wait beyond their configured deadline as expired. The final state keeps a reason and the last completed step for inspection.',
    'priya',
    'Expiration is terminal, but it must not delete the last checkpoint needed to explain partial work.',
    'jobs/workflow-timeout.ts',
    '+ if (now > workflow.deadline) return expireWithContext(workflow)',
  ),
  record(
    155,
    'Deduplicate workflow wake-up events',
    'rafael',
    '2026-01-28',
    ['background-jobs', 'billing'],
    'Records a wake-up event key before advancing a waiting workflow. Repeated billing notifications cannot advance the same step twice.',
    'jonas',
    'Use the source event ID as the key; a timestamp would not identify duplicate deliveries reliably.',
    'jobs/wakeup.ts',
    '+ if (await seen.insertUnique(event.id)) await advance(workflow)',
  ),
  record(
    156,
    'Sketch the first workflow state transitions',
    'rafael',
    '2025-10-15',
    ['background-jobs'],
    'Adds historical state transitions for pending, running, and completed work. Retry and timeout states arrived in later PRs.',
    'leah',
    'The transition table makes illegal jumps visible; add a test for completion from pending.',
    'jobs/workflow-state.ts',
    '+ assertTransition(currentState, nextState)',
  ),
  record(
    157,
    'Resume batch exports from a durable cursor',
    'celine',
    '2026-06-07',
    ['background-jobs'],
    'Stores a durable cursor after each committed export page. Restarting a worker resumes at the next page without duplicating already published output.',
    'rafael',
    'The cursor and output commit need one boundary; otherwise a crash between them may skip a page.',
    'jobs/batch-cursor.ts',
    '+ await commitPageAndCursor(page, nextCursor)',
  ),
  record(
    158,
    'Explain failed jobs in operator view',
    'celine',
    '2026-04-22',
    ['background-jobs', 'observability'],
    'Shows a safe failure category, last attempt, and next action for failed batch jobs. Raw payload contents stay out of the operator view.',
    'nora',
    'The category should help triage while avoiding raw exception text that may contain customer data.',
    'jobs/operator-view.ts',
    '+ return { category: safeFailure(error), lastAttemptAt, retryable }',
  ),
  record(
    159,
    'Honor cancellation between export pages',
    'celine',
    '2026-03-13',
    ['background-jobs'],
    'Checks cancellation after each committed page rather than only before the job begins. A canceled export retains a clear partial-output status.',
    'priya',
    'The status must not say complete when a page was written before the cancellation check.',
    'jobs/export-cancel.ts',
    '+ if (await canceled(job.id)) return markPartial(job)',
  ),
  record(
    160,
    'Create the original batch progress counter',
    'celine',
    '2025-07-29',
    ['background-jobs'],
    'Adds a historical completed-item counter for batch work. Later durable cursors and partial-output states provide stronger recovery semantics.',
    'leah',
    'Count committed items only; an attempted item may be retried after the worker restarts.',
    'jobs/progress.ts',
    '+ progress.completed += committedItems.length',
  ),
  record(
    161,
    'Link request and job spans with safe context',
    'yusuf',
    '2026-06-16',
    ['observability'],
    'Propagates a trace parent across enqueue and execution without treating the identifier as authorization. Missing parent context starts a new trace safely.',
    'nora',
    'A background retry should keep a link to the original request while receiving its own execution span.',
    'telemetry/job-link.ts',
    '+ span.link(enqueueContext.traceId)\n+ span.setAttribute("job.id", job.id)',
  ),
  record(
    162,
    'Limit high-cardinality metric labels',
    'yusuf',
    '2026-04-24',
    ['observability'],
    'Replaces customer and job identifiers in metric labels with bounded categories. Detailed identifiers remain available only in sampled traces.',
    'grace',
    'The bounded label set keeps dashboards comparable as customer volume grows.',
    'telemetry/metric-labels.ts',
    '+ countJob({ kind: safeJobKind(job), outcome })',
  ),
  record(
    163,
    'Sample slow job traces with consistent rules',
    'yusuf',
    '2026-02-03',
    ['observability', 'background-jobs'],
    'Keeps traces for jobs over a duration threshold while sampling ordinary successes. Failures are retained regardless of the routine sample rate.',
    'priya',
    'The failure override needs to run after the outcome is known, not at job start.',
    'telemetry/job-sampling.ts',
    '+ if (failed || durationMs > slowThreshold) retainTrace(span)',
  ),
  record(
    164,
    'Define the first shared trace attribute list',
    'yusuf',
    '2025-09-08',
    ['observability'],
    'Introduces an early allow-list for trace attributes across services. It predates later cardinality and sensitive-field controls.',
    'leah',
    'The allow-list is a good start; keep request bodies outside the approved attributes.',
    'telemetry/attributes-v1.ts',
    '+ const allowed = ["route", "method", "status"]',
  ),
  record(
    165,
    'Group related alert signals into one incident view',
    'grace',
    '2026-06-20',
    ['observability'],
    'Groups queue delay and elevated failure metrics under one triage view when they share a service and time window. It does not prescribe recovery actions.',
    'nora',
    'Keep the underlying alerts visible so a reviewer can see which signal caused the grouping.',
    'observability/alert-group.ts',
    '+ return groupSignals({ service, windowMinutes: 10 })',
  ),
  record(
    166,
    'Add alert evaluation windows for noisy failures',
    'grace',
    '2026-04-12',
    ['observability'],
    'Requires an elevated failure rate across multiple windows before paging. A single sparse interval remains visible on the dashboard without waking someone.',
    'yusuf',
    'The denominator should exclude missing traffic; zero requests cannot imply a healthy error rate.',
    'observability/alert-window.ts',
    '+ page = windows.every(window => window.requests > 0 && window.failureRate > limit)',
  ),
  record(
    167,
    'Annotate alerts with recent deployment references',
    'grace',
    '2026-01-26',
    ['observability'],
    'Adds deployment IDs and change windows to an alert detail view. The annotation helps triage correlation but does not claim a deployment caused a failure.',
    'quentin',
    'The UI should label this as nearby change context, not as an identified root cause.',
    'observability/change-context.ts',
    '+ alert.context.recentDeployments = deployments.near(alert.startedAt)',
  ),
  record(
    168,
    'Introduce historical queue delay alert',
    'grace',
    '2025-10-02',
    ['observability'],
    'Adds an early queue-delay alert with a fixed threshold. Later evaluation windows and grouped signals improve its interpretation.',
    'priya',
    'Show queue depth alongside wait time so an operator can distinguish sustained backlog from a short spike.',
    'observability/queue-alert.ts',
    '+ if (queueWaitP95 > threshold) notifyTriage()',
  ),
  record(
    169,
    'Generate a local trace timeline from sample events',
    'quentin',
    '2026-06-02',
    ['observability'],
    'Builds a local timeline view from safe sample trace events. It makes spans easier to follow without connecting to a production telemetry service.',
    'yusuf',
    'Sort by start time and preserve parent links; arrival order can differ from execution order.',
    'devtools/trace-timeline.ts',
    '+ return spans.sort(byStartTime).map(withParentLabel)',
  ),
  record(
    170,
    'Show missing trace links explicitly',
    'quentin',
    '2026-05-14',
    ['observability'],
    'Marks spans with absent parent context rather than drawing an invented edge. The view distinguishes a sampling gap from a confirmed root span.',
    'nora',
    'The missing-link marker is more honest than a disconnected line that looks like a new request.',
    'devtools/trace-links.ts',
    '+ if (!knownParent(span)) markContextGap(span)',
  ),
  record(
    171,
    'Collect a compact job diagnosis bundle',
    'quentin',
    '2026-02-24',
    ['observability', 'background-jobs'],
    'Assembles safe job state, attempt history, and trace references for local diagnosis. It excludes payload bodies and account secrets.',
    'celine',
    'Include checkpoint version so a failed export can be compared with the workflow implementation used.',
    'devtools/job-bundle.ts',
    '+ return { state, attempts, checkpointVersion, traceIds }',
  ),
  record(
    172,
    'Add the first development trace viewer',
    'quentin',
    '2025-08-21',
    ['observability'],
    'Introduces a historical local trace list for development samples. Later parent-link and context-gap views provide deeper diagnosis.',
    'leah',
    'Keep this viewer sample-only; it should not become a hidden route to production traces.',
    'devtools/traces.ts',
    '+ return sampleSpans.map(renderTraceRow)',
  ),
]
