/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=worker/wrangler.jsonc --include-runtime=false worker/env.d.ts` (hash: 71106e451181370eb8e597d6b0db308e)
interface __BaseEnv_Env {
	PER_VISITOR: RateLimit;
	PER_LOCATION: RateLimit;
	BUDGET: DurableObjectNamespace<import("./index").DailyBudget>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
		durableNamespaces: "DailyBudget";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
